In [1]:
import numpy as np
import pandas as pd
import matplotlib
from matplotlib import pyplot as plt
from sklearn.preprocessing import MinMaxScaler
from sklearn.model_selection import KFold
from sklearn.metrics import confusion_matrix
from sklearn.metrics import recall_score
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier

In [ ]:
from pydantic import BaseModel

class Player(BaseModel):
    name:str
    GP:int







In [2]:
def score_classifier(dataset,classifier,labels):

    """
    performs 3 random trainings/tests to build a confusion matrix and prints results with precision and recall scores
    :param dataset: the dataset to work on
    :param classifier: the classifier to use
    :param labels: the labels used for training and validation
    :return:
    """

    kf = KFold(n_splits=3,random_state=50,shuffle=True)
    confusion_mat = np.zeros((2,2))
    recall = 0
    for training_ids,test_ids in kf.split(dataset):
        training_set = dataset[training_ids]
        training_labels = labels[training_ids]
        test_set = dataset[test_ids]
        test_labels = labels[test_ids]
        classifier.fit(training_set,training_labels)
        predicted_labels = classifier.predict(test_set)
        confusion_mat+=confusion_matrix(test_labels,predicted_labels)
        recall += recall_score(test_labels, predicted_labels)
    recall/=3
    print(confusion_mat)
    print(recall)

In [7]:
df = pd.read_csv(".\\Test Data Science/nba_logreg.csv")
print(df.shape)
df.head(5)

(1340, 21)


Name  GP   MIN  PTS  FGM  FGA   FG%  3P Made  3PA   3P%  ...  \
0   Brandon Ingram  36  27.4  7.4  2.6  7.6  34.7      0.5  2.1  25.0  ...   
1  Andrew Harrison  35  26.9  7.2  2.0  6.7  29.6      0.7  2.8  23.5  ...   
2   JaKarr Sampson  74  15.3  5.2  2.0  4.7  42.2      0.4  1.7  24.4  ...   
3      Malik Sealy  58  11.6  5.7  2.3  5.5  42.6      0.1  0.5  22.6  ...   
4      Matt Geiger  48  11.5  4.5  1.6  3.0  52.4      0.0  0.1   0.0  ...   

   FTA   FT%  OREB  DREB  REB  AST  STL  BLK  TOV  TARGET_5Yrs  
0  2.3  69.9   0.7   3.4  4.1  1.9  0.4  0.4  1.3          0.0  
1  3.4  76.5   0.5   2.0  2.4  3.7  1.1  0.5  1.6          0.0  
2  1.3  67.0   0.5   1.7  2.2  1.0  0.5  0.3  1.0          0.0  
3  1.3  68.9   1.0   0.9  1.9  0.8  0.6  0.1  1.0          1.0  
4  1.9  67.4   1.0   1.5  2.5  0.3  0.3  0.4  0.8          1.0  

[5 rows x 21 columns]

In [8]:
names = df['Name'].values.tolist() # players names
labels = df['TARGET_5Yrs'].values # labels
paramset = df.drop(['TARGET_5Yrs','Name'],axis=1).columns.values
df_vals = df.drop(['TARGET_5Yrs','Name'],axis=1).values

In [10]:
df_vals

array([[36. , 27.4,  7.4, ...,  0.4,  0.4,  1.3],
       [35. , 26.9,  7.2, ...,  1.1,  0.5,  1.6],
       [74. , 15.3,  5.2, ...,  0.5,  0.3,  1. ],
       ...,
       [43. , 12.1,  5.4, ...,  0.3,  0.4,  0.9],
       [52. , 12. ,  4.5, ...,  0.4,  0.1,  0.8],
       [47. , 11.7,  4.4, ...,  0.7,  0.1,  0.9]])

In [1]:
from fastapi import FastAPI, Path
import pickle
from pydantic import BaseModel

app = FastAPI()

model = pickle.load(open("model", 'rb'))

C:\Users\simon\anaconda3\lib\site-packages\sklearn\base.py:329: UserWarning: Trying to unpickle estimator LogisticRegression from version 1.1.1 when using version 1.0.2. This might lead to breaking code or invalid results. Use at your own risk. For more info please refer to:
https://scikit-learn.org/stable/modules/model_persistence.html#security-maintainability-limitations
  warnings.warn(


In [38]:
class Player(BaseModel):
    name:str
    GP:int
    MIN:float
    PTS:float
    FGM:float
    FGA:float
    FGp:float
    threePointsMade:float
    threePointsAttempts:float
    threePointsPercent:float
    FTM:float
    FTA:float
    FTp:float
    OREB:float
    DREB:float
    REB:float
    AST:float
    STL:float
    BLK:float
    TOV:float


In [50]:
player = Player(
    name="Bryan",
    GP=0,
    MIN=0,
    PTS=0,
    FGM=0,
    FGA=0,
    FGp=0,
    threePointsMade=0,
    threePointsAttempts=0,
    threePointsPercent=0,
    FTM=0,
    FTA=0,
    FTp=0,
    OREB=0,
    DREB=0,
    REB=0,
    AST=0,
    STL=0,
    BLK=0,
    TOV=0,
)

In [44]:
model.predict([list(joueur1.__dict__.values())[1:]])

array([0])

In [51]:
    
    player_array = [[
                    player.GP,
                    player.MIN,
                    player.PTS,
                    player.FGM,
                    player.FGA,
                    player.FGp,
                    player.threePointsMade,
                    player.threePointsAttempts,
                    player.threePointsPercent,
                    player.FTM,
                    player.FTA,
                    player.FTp,
                    player.OREB,
                    player.DREB,
                    player.REB,
                    player.AST,
                    player.STL,
                    player.BLK,
                    player.TOV 
                    ]]
        

In [53]:
model.predict(player_array)

array([0])

In [32]:
[list(joueur1.__dict__.values())[1:]]

[[1,
  1.0,
  1.0,
  1.0,
  1.0,
  1.0,
  1.0,
  1.0,
  1.0,
  1.0,
  1.0,
  1.0,
  1.0,
  1.0,
  1.0,
  1.0]]